version = 0.1

[default.deploy.parameters]
stack_name = "mision-emprende-dev"
resolve_s3 = true
s3_prefix = "mision-emprende-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Entorno=\"dev\" OrigenCors=\"*\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
