export const FASES_ORDEN = [
  "configuracion",
  "f1_bienvenida",
  "f1_conocidos",
  "f1_pre_sopa",
  "f1_sopa",
  "f1_ranking",
  "mapa_f2_empatia",
  "f2_transicion",
  "f2_tematicas",
  "f2_transicion_empatia",
  "f2_bubblemap",
  "f2_ranking",
  "mapa_f3_creatividad",
  "f3_transicion_creatividad",
  "f3_lego",
  "f3_ranking",
  "mapa_f4_final",
  "f4_transicion_comunicacion",
  "f4_construccion_pitch",
  "f4_orden_pitch",
  "f4_presentacion_pitch",
  "f5_transicion_apoyo",
  "f5_evaluacion_pitch",
  "f6_ranking",
  "reflexion",
] as const;

export type FaseSesion = (typeof FASES_ORDEN)[number];

export const TIEMPOS_POR_FASE: Record<string, number> = {
  configuracion: 0,
  f1_bienvenida: 0,
  f1_conocidos: 10,
  f1_pre_sopa: 0,
  f1_sopa: 60,
  f1_ranking: 0,
  mapa_f2_empatia: 0,
  f2_transicion: 0,
  f2_tematicas: 120,
  f2_transicion_empatia: 0,
  f2_bubblemap: 60,
  f2_ranking: 0,
  mapa_f3_creatividad: 0,
  f3_transicion_creatividad: 0,
  f3_lego: 15,
  f3_ranking: 0,
  mapa_f4_final: 0,
  f4_transicion_comunicacion: 0,
  f4_construccion_pitch: 120,
  f4_orden_pitch: 0,
  f4_presentacion_pitch: 90,
  f5_transicion_apoyo: 0,
  f5_evaluacion_pitch: 90,
  f6_ranking: 0,
  reflexion: 0,
};
